schema_version = "1.0.0"

id = "PieMenusPlus"
version = "2.0.0"
name = "Pie Menus Plus"
tagline = "Improved Pie Menu ecosystem for Blender 5.0+"
maintainer = "Tabzy"
website = "https://github.com/CloudyTabzy/PieMenusPlus"
type = "add-on"

tags = ["3D View",]

blender_version_min = "5.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
